cyberark/ansible-conjur-collection

- CHANGELOG.md
- Jenkinsfile
- bin/parse-changelog.sh
- bin/test.sh
- tests/Dockerfile
- tests/Dockerfile_nginx
- tests/docker-compose.yml
- tests/policy/root.yml
- tests/proxy/default.conf
- tests/proxy/ssl.conf
- tests/test.sh
- tests/test_cases/retrieve-secret/playbook.yml
- tests/test_cases/retrieve-secret/tests/test_default.py
Connected to #6 
This PR adds automated tests to the project. It runs a playbook that retrieves a Conjur secret into an Ansible variable.
Additional tests can be added to the `test_cases` directory in a similar way.
> Add automated tests

- CHANGELOG.md
- plugins/lookup/conjur_variable.py
Connected to ansible/awx#7191
Blocked by #7 
Previously we used `urllib.parse`'s `quote_plus` function
to encode strings. However, this method replaces spaces with
`+` instead of `%20` which resulted in a 404 Not Found error
as in the server side we interpret `%20` as a space and leave
the `+` as it is.
More info can be found in the definition of `quote_plus`: https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus
> Encode spaces correctly

- CHANGELOG.md
- plugins/lookup/conjur_variable.py
- tests/policy/root.yml
- tests/test.sh
- tests/test_cases/retrieve-variable-with-spaces-secret/playbook.yml
- tests/test_cases/retrieve-variable-with-spaces-secret/tests/test_default.py
Connected to #12 
The `quote` method's default value for `safe` is '/' so it doesn't encode slashes
into "%2F" which is what the Conjur server expects. Thus, we need to use this
method with no safe characters. We can't use the method `quote_plus` (which encodes
slashes correctly) because it encodes spaces into the character '+' instead of "%20"
as expected by the Conjur server
> Encode spaces and slashes correctly

- bin/build_release
Without this, it's possible that the base OS doesn't have ansible-galaxy
installed and that the build will fail (Jenkins).
> Made ansible-galaxy release building use a Docker image

- bin/build_release
Since Jenkins doesn't have an interactive terminal, we can't use that
flag with docker.
> Remove opening of input stream for release building

- Jenkinsfile
We need to build artifacts both when we are on the master
branch, and when we are performing a tagged build
> Add additional condition for artifact building stage

- CHANGELOG.md
- README.md
- plugins/lookup/conjur_variable.py
- tests/conjur_variable/policy/root.yml
- tests/conjur_variable/test.sh
- tests/conjur_variable/test_cases/retrieve-variable-into-file/env
- tests/conjur_variable/test_cases/retrieve-variable-into-file/playbook.yml
- tests/conjur_variable/test_cases/retrieve-variable-into-file/tests/test_default.py
This PR offers a new option:  ~~file_mode~~ **as_file** (boolean) which adds the possibility to **store a secret as a file** in ~~/dev/shm~~ a temporary file instead of returning it directly. The lookup function instead returns the path of the file.
This feature addresses an issue with ansible_ssh_private_key_file which doesn't accept inline ssh keys. 
By adding this option, it is now possible to use the below lookup with ansible_ssh_private_key_file:
```yaml
ansible_ssh_private_key_file: "{​​{​​ lookup('cyberark.conjur.conjur_variable', 'path/to/secret-id', as_file=True) }​​}​​"
```
Without the need to handle temporary file creation in playbooks, it extends the current support of the below:
```yaml
ansible_password: "{​​{​​ lookup('cyberark.conjur.conjur_variable', 'path/to/secret-id') …
```
> Add lookup plugin option (file_mode) to store secret in a file

- README.md
- ci/test.sh
- roles/conjur_host_identity/tests/Dockerfile
- roles/conjur_host_identity/tests/ansible.cfg
- roles/conjur_host_identity/tests/docker-compose.yml
- roles/conjur_host_identity/tests/inventory-playbook.yml
- roles/conjur_host_identity/tests/test.sh
- roles/conjur_host_identity/tests/test_cases/configure-conjur-identity/playbook.yml
- roles/conjur_host_identity/tests/test_cases/configure-conjur-identity/tests/test_default.py
Fix broken CI
1. Standardise on the base container image for running ansible tests. Change image used by `conjur_host_identity` to match `conjur_variable`.
2.  Explicitly set the ANSIBLE_CONFIG envvar to avoid Ansible ignoring the configuration because it is in a world-writable working directory, see https://docs.ansible.com/ansible/latest/reference_appendices/config.html#avoiding-security-risks-with-ansible-cfg-in-the-current-directory.
Resolves N/A
CyberArk internal issue link: [insert issue ID]()
N/A
changes, or
> Fix conjur_host_identity tests

- .github/workflows/ansible-test.yml
- README.md
- ci/test.sh
- roles/conjur_host_identity/tests/Dockerfile
- roles/conjur_host_identity/tests/ansible.cfg
- roles/conjur_host_identity/tests/docker-compose.yml
- roles/conjur_host_identity/tests/inventory-playbook.yml
- roles/conjur_host_identity/tests/test.sh
- roles/conjur_host_identity/tests/test_cases/configure-conjur-identity/playbook.yml
- roles/conjur_host_identity/tests/test_cases/configure-conjur-identity/tests/test_default.py
- tests/conjur_variable/test.sh
- tests/sanity/ignore-2.13.txt
End support for Python 2.x, remove Python 3.7
Also merged in the changes from @doodlesbykumbi from PR #70 
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained.
pip 21.0 will drop support for Python 2.7 in January 2021.
More details about Python 2 support in pip can be found at
https://pip.pypa.io/en/latest/development/release-process/#python-2-support
CI tests should pass.
Resolves #68
CyberArk internal issue link: [insert issue ID]()
merged.*
changes, or
> Remove Python 3.7, 2.x

- .github/workflows/ansible-test.yml
- dev/Dockerfile
- dev/docker-compose.yml
- plugins/lookup/conjur_variable.py
- roles/conjur_host_identity/tests/Dockerfile
- tests/conjur_variable/Dockerfile
- tests/sanity/ignore-2.14.txt
In its current state, the development environment was silently failing during setup.
The `conjur-host-identity` role was incorrectly mounted into the Ansible control node container, so using it to set up Conjur identities on the managed nodes silently failed.
Addressed some other bugs while I was in the repo.
- The `conjur-host-identity` role directory is mounted into the Ansible control node container for the development environment.
- Add collection sanity test against Ansible 2.11 and 2.12.
- Add `tests/sanity/ignore-2.14.txt`.
- Remove @cyberark/community-and-integrations-team from `conjur_variable` plugin authors. Not only does [Ansible's module validation only allow GitHub usernames for individual contributors](https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_util …
> Bugfix: Mount role directory into Ansible container

- roles/conjur_host_identity/tests/inventory-playbook-v2.yml
- roles/conjur_host_identity/tests/inventory-v2.j2
- roles/conjur_host_identity/tests/test.sh
- tests/conjur_variable/docker-compose.yml
- tests/conjur_variable/test_cases/retrieve-variable-bad-cert-path/tests/test_default.py
- tests/conjur_variable/test_cases/retrieve-variable-bad-certs/tests/test_default.py
- tests/conjur_variable/test_cases/retrieve-variable-disable-verify-certs/tests/test_default.py
- tests/conjur_variable/test_cases/retrieve-variable-into-file/tests/test_default.py
- tests/conjur_variable/test_cases/retrieve-variable-no-cert-provided/tests/test_default.py
- tests/conjur_variable/test_cases/retrieve-variable-with-authn-token-bad-cert/tests/test_default.py
- tests/conjur_variable/test_cases/retrieve-variable-with-authn-token/tests/test_default.py
- tests/conjur_variable/test_cases/retrieve-variable-with-spaces-secret/tests/test_default.py
- tests/conjur_variable/test_cases/retrieve-variable/tests/test_default.py
Tests should pass both with docker-compose v1 (as on Jenkins) and v2 (as on local machines).
Docker Compose v2 changes the default naming convention for containers, from '_' to '-'. To support both v1 and v2, explicitly set the container_name in docker-compose.yml for the conjur_variable tests.
For the roles/conjur_host_identity tests we can't use container_name because we use scaling, and docker-compose doesn't support specifying a container_name when requiring multiple instances of a container. Instead we use different inventory.j2 template files for the different docker-compose versions.
- Conjur_variable tests: Updated docker-compose.yml to explicitly set container_name
- Conjur_variable tests: Updated tests to use the new container name
- Roles/conjur_host_identity tests: Use …
> Fix tests on docker-compose v2

- plugins/lookup/conjur_variable.py
The conjur_variable lookup should validate the provided Conjur variable path. Error messages regarding invalid secret path inputs should be more accurate and descriptive. 
Code changes are in conjur_variable plugin  to cover all Conjur variable path issues .
CyberArk internal issue link: [ONYX-15265](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-15265)
merged.*
changes, or
> Validate variable paths given to Lookup plugin

- roles/conjur_host_identity/tests/test.sh
- roles/conjur_host_identity/tests/test_app_ubuntu/Dockerfile
- roles/conjur_host_identity/tests/test_cases/misconfig-conjur-identity/playbook.yml
For conjur_host_identity role , there should be expansion to cover failing cases, where using the role fails due to some sort of misconfiguration.
Added `roles/conjur_host_identity/tests/test_cases/misconfig-conjur-identity/`.
CyberArk internal issue link: [ONYX-15262](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-15262)
merged.*
changes, or
> Add negative test case for Conjur Role

- dev/Dockerfile
- dev/playbooks/inventory-setup/inventory-playbook-v2.yml
- dev/playbooks/inventory-setup/inventory-v2.j2
- dev/playbooks/inventory-setup/inventory.j2
- dev/start.sh
- dev/test_app_centos/Dockerfile
- dev/test_app_ubuntu/Dockerfile
- roles/conjur_host_identity/tests/Dockerfile
- tests/conjur_variable/Dockerfile
Jenkins builds were failing with the following logs when building the Ansible service:
```
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
```
This error occurs when running `apt-get` commands in Ubuntu 22.04 in Docker <= 20.10.9.
These Dockerfiles have been pinned to Ubuntu 20.04.
- Dev env scripts now support `docker-compose` v1 and v2.
- Ubuntu-based Dockerfiles are pinned to 20.04.
CyberArk internal issue link: [ONYX-19624](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-19624)
merged.*
changes, or
> Jenkins and dev environment bugfixes

- Jenkinsfile
- dev/test_unit.sh
- tests/unit/requirements.txt
Generate test coverage reporting in CI, to ensure that the repo is sufficiently unit tested.
Jenkins file and test_unit script file
CyberArk internal issue link: [ONYX-15264](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-15264)
Implement code coverage reporting in CI, either with ccCoverage or ansible-test
Investigate whether the ccCoverage Jenkins plugin can be used for the Collection repo
changes, or
> Report Lookup plugin unit test coverage to Jenkins

- .github/workflows/ansible-test.yml
- Jenkinsfile
- ci/test.sh
- roles/conjur_host_identity/tests/Dockerfile
- roles/conjur_host_identity/tests/docker-compose.yml
- roles/conjur_host_identity/tests/test.sh
- tests/conjur_variable/Dockerfile
- tests/conjur_variable/docker-compose.yml
- tests/conjur_variable/test.sh
For an Ansible Collection to be certified by RedHat, it needs to be tested against at least two versions of Ansible Core.
This PR allows for the tests in the Collection to be configured to run against a particular Ansible major version, and updates the Jenkinsfile to run tests against Ansible 5 and 6, which corresponds to Ansible Core 2.12 and 2.13, respectively.
CyberArk internal issue link: [ONYX-24058](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-24058)
merged.*
changes, or
> Test collection against Ansible versions 5 and 6 in Jenkins

- .github/workflows/ansible-test.yml
- Jenkinsfile
- ci/parse-changelog.sh
- dev/Dockerfile
- dev/Dockerfile_nginx
- dev/test_unit.sh
- roles/conjur_host_identity/tests/Dockerfile_nginx
- tests/conjur_variable/Dockerfile_nginx
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.13.txt
- tests/sanity/ignore-2.14.txt
- tests/sanity/ignore-2.9.txt
- updates Jenkins pipeline to utilize parseChangelog tool
changes, or
> Updated Jenkins pipeline to use parseChangelog utility

- dev/docker-compose.yml
- dev/start.sh
- roles/conjur_host_identity/tests/docker-compose.yml
- roles/conjur_host_identity/tests/test.sh
- tests/conjur_variable/docker-compose.yml
- tests/conjur_variable/test.sh
Add `--no-deps` flag to any CLI container commands. Since `conjur` is a linked service in docker-compose.yml, it is attempting to restart conjur each time the CLI container is run
Also updates the test/dev scripts to use Conjur CLI v8
> Fix builds

- ci/test.sh
- dev/start.sh
- roles/conjur_host_identity/tasks/identity_check.yml
- roles/conjur_host_identity/tests/test_cases/bad-ssl-config/playbook.yml
- roles/conjur_host_identity/tests/test_cases/not-conjurized/playbook.yml
Fix Jenkins build:
```
[2023-09-19T14:26:02.124Z] TASK [Confirm error message] ***************************************************
[2023-09-19T14:26:02.124Z] fatal: [dev-test_app_ubuntu-1]: FAILED! => {
[2023-09-19T14:26:02.124Z]     "assertion": "ansible_failed_result.msg == \"'conjur_appliance_url' is undefined. 'conjur_appliance_url' is undefined\"",
[2023-09-19T14:26:02.124Z]     "changed": false,
[2023-09-19T14:26:02.124Z]     "evaluated_to": false,
[2023-09-19T14:26:02.124Z]     "msg": "Assertion failed"
[2023-09-19T14:26:02.124Z] }
[2023-09-19T14:26:02.379Z] fatal: [dev-test_app_ubuntu-2]: FAILED! => {
[2023-09-19T14:26:02.379Z]     "assertion": "ansible_failed_result.msg == \"'conjur_appliance_url' is undefined. 'conjur_appliance_url' is undefined\"",
[2023-09-19T14:26:02.379Z] …
```
> Bugfixes: env consolidation, error wrapping

- CHANGELOG.md
- README.md
- galaxy.yml
- meta/runtime.yml
Address issues with the previous version uploading to Automation Hub:
- `dev` folder included in binary, resulting in sanity check and linting errors
- Bump `requires_ansible` key to `>= 2.13`
Also preps to release a new version (v1.2.2) with these changes
> Remove conjur-intro submodule from build

- CONTRIBUTING.md
- dev/start.sh
- dev/stop.sh
- dev/test_app_centos/Dockerfile
- dev/test_app_ubuntu/Dockerfile
- dev/util.sh
- Use Docker Compose v2
- Update ubuntu and centos base images
- Replace `docker-compose` with `docker compose`
- Update centos image to v8
- Update ubuntu image to 22.04
CyberArk internal issue ID: CNJR-2127
merged.*
changes, or
> Update Docker Compose Syntax, base images
